### ISSUE TITLE
Undocumented requirement for Chrome to run unit tests

### ISSUE THREAD

**Issue by nklincoln** [fabric-composer/fabric-composer#108]
Following a fresh installation on a 'vanilla' Ubuntu machine and a clone of fabric-composer, running the unit suite via 'npm test' will result in test failures.

The failures are at the 'karma start single run' command, and are due to a dependency on Chrome within the test, which attempts to launch a Chrome browser. 

The dependency should be documented in the "getting started prerequisites.html", but there is an additional question to placing a conditional installation of Chrome in prereqs-ubuntu.sh within the getting started scripts.

**Comment by sstone1** [comment]
@nklincoln I think that Chrome should only be a prerequisite for developers, so it needs to go in the contributing guide rather than the public documentation for users.
