### ISSUE TITLE
404 Error's on all Related Reference Links

### ISSUE THREAD

**Issue by Tobias-Hunter** [fabric-composer/fabric-composer#111]
Under Docs/Concepts/Participants and Transactions the "Related Reference" links are broken...

Please see photo:

![Screen Shot 2017-02-08 at 10.21.52](http://static.gitscout.com/a4c0e5b38b01135138c7e0b2b8c37a2f111c394eb2de02a7232e41358ef8a97c.png)

Fix:
"Participant add command" should link to here: https://fabric-composer.github.io/tasks/participant-add.html
"Identity issue command"  to here: https://fabric-composer.github.io/tasks/identity-revoke.html
"Identity revoke command" to here: https://fabric-composer.github.io/tasks/identity-revoke.html

**Comment by Jakeeyturner** [comment]
[Fixed in PR](https://github.com/fabric-composer/fabric-composer/pull/129)
