### ISSUE TITLE
Loopback connector should give us the ability to resolve relationships

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#115]
When getting assets with the rest API, there should be an option for relationships to resolved.

e.g. 
```
Animal {
   type: "SHEEP_GOAT",
   owner: {
        id: "FARMER1",
       name: "Farmer Steve"
   }
}
```
rather than 
```
Animal {
   type: "SHEEP_GOAT",
   owner: "FARMER1"
}
```

**Comment by samjsmith** [comment]
I pinged a colleague on this and he said ```its possible to pass the parameter to metadata calls... and the connector will receive them 
 however for instances API /instances/thing, I believe it does not go till the connector and the provider resolves the call by just using the RETRIEVE api of connector```
I'm not quite sure exactly what he means so I'll ping again tomorrow when he comes online.

**Comment by samjsmith** [comment]
Current thinking is that we could use an Include filter (https://loopback.io/doc/en/lb2/Include-filter.html) to allow clients to specify whether they want the fully resolved object back or not.  I think it would be relatively easy to support this and would mean that you'd just need to set a filter of {"include":"resolve"} with the GET request.

**Comment by samjsmith** [comment]
I believe that this one is done now.
