### ISSUE TITLE
Getting started documentation shows SSH URLs

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#120]
Issue reported by Tetiana on the Hyperledger RocketChat; an access denied error when trying to run a `git clone` command.

From https://fabric-composer.github.io/start/getting-started-cmd-line.html

_Clone the Repository and Install Dependencies
First clone the repository:_

```
git clone git@github.com:fabric-composer/sample-networks.git
cd sample-networks/packages/DigitalProperty-Network
npm install
```

We should use `https://` instead of `git@` GitHub URLs as you can clone without having to perform any SSH setup.

**Comment by Jakeeyturner** [comment]
[Fixed in this PR](https://github.com/fabric-composer/fabric-composer/pull/129)
