### ISSUE TITLE
As a user I can supply the metadata for my business network in Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#130]
We need to be able supply a name and a version for the business network. More advanced users may want to edit package.json.

**Comment by EdMoffatt** [comment]
Editing the name and version is shown in pages 8+9 of the latest low-fi, available here: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

Note that whilst the "Script" and "ACL" screens are not yet included in these mockups, they too would have the same metadata display/edit functions
