### ISSUE TITLE
A missing word asset on the "but What is asset" page.

### ISSUE THREAD

**Issue by xufengli** [fabric-composer/fabric-composer#131]
A word asset is missing after an on this page: 
https://w3-03.sso.ibm.com/TFIM/sps/auth?FedName=IBM_W3_SAML20_INTERNAL1&FedId=uuid3cfe4e97-0139-183a-bdf6-a016685ce30d

**Comment by dselman** [comment]
Please correct the link in the defect report.

**Comment by xufengli** [comment]
The link seems not to be valid anymore  and I could not find the Asset page on the document.
I am happy to close this issue and I will reopen it when I see it again.

**Comment by xufengli** [comment]
I reopen this issue as I find the problem is in the section **But what is an asset?** on the **Running a sample with the CLI** .

**Comment by xufengli** [comment]
Issue is fixed now so close it.
