### ISSUE TITLE
As a user I can use Composer Playground on the public Internet

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#133]
Web connection profile only

**Comment by EdMoffatt** [comment]
Note that the latest version of the low-fi designs is focussed on describing the function of the public internet version of Playground: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

**Comment by samjsmith** [comment]
This involves getting a process to publish the new Playground app up to Bluemix.
WE need to change the top level Travis build script to push Playground instead of Composer.
And then to delete Composer.

**Comment by samjsmith** [comment]
I've given this one to you @mbwhite since I have no idea where to change this.
