### ISSUE TITLE
As a user I can export a business network archive from Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#136]
Provide the ability to download the artifacts being edited as a business network archive (zip file). This would allow them to be deployed using `composer network deploy` or unzipped and edited using Atom or VS Code.

**Comment by EdMoffatt** [comment]
This will live on the "Define" tab of the UI (see most of the early pages in the latest low-fi, available here: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/ )

Ideally, hitting Export results in an archive being downloaded via usual Browser download mechanisms, named according to the metadata of the Business Network Definition.  If we need any more detail on this though, give me a shout!

**Comment by samjsmith** [comment]
Pop up a file selection to allow you to specify where the .bna file is to be saved to.
Alhtough it's a zip file we'll call it a .bna file (business network archive) to imply that the zip requires a certain structure.

**Comment by EdMoffatt** [comment]
Now included in the latest low-fis, page 22-24 (though basically it says "we'll use a Browser "Save As" dialog" ;)
https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

**Comment by Jakeeyturner** [comment]
[Will close this issue once PR is merged](https://github.com/fabric-composer/fabric-composer/pull/262)
