### ISSUE TITLE
As a user I can view a README.md file within Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#138]
We should make business network definitions self-documenting, by allowing the author to include a README.md file that is displayed inside Playground.

**Comment by EdMoffatt** [comment]
Readme for a sample network is shown when it's first imported (and accessible from the side-nav in Define) - see pages 2 and 6 of the latest low-fi designs, available here: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

Need to make sure we get hold of a list of all the samples we intend to include for next round of demos, and make sure we have readmes for all of them, ideally with illustrations for any that we intend to demo (suggest at least Basic Sample and whatever we're likely to demo).

Illustrations could be either me or Sam - handing to Sam for now to add the hi-fis, and then we can leave it with him or ping it over to me accordingly once we see who's got spare cycles!

**Comment by samjsmith** [comment]
We need to add the basic sample into the networks sample github to be one of the possible 5 samples that can be deployed

**Comment by winslet** [comment]
Hifi below:

![Fabric_Composer_Playground_Readme_SW_1](http://static.gitscout.com/5ec41bc605685c8b23275efae4cc9d3ab1ebb485b6150c5f4e0cd8de514db200.png)

Marketch Available for redlines (but please review design before putting live). Spacing's may not be totally accurate as of now, but please scale each odd measurement to the nearest 0.25rem (where 1rem = 16px). 

[Fabric_Composer_Playground_Readme_SW_1.zip](http://static.gitscout.com/ff6bd7fd834f5a9b8ed9700c4e2dafec06f797fa97120d6f4a3dff3e6dc55115.zip)

Any questions please let me know.

**Comment by EdMoffatt** [comment]
Another quick thought on this one...  Right now, we include the licensing information at the top of the script file in the sample networks.  Do we want to keep it there, or do we want to move it to the Readme when we add these in?
(Don't have a strong opinion either way, just saw it there and thought "hmm, maybe...")

**Comment by caroline-church** [comment]
i think the script file is fine, i think it would clutter up the read me quite alot if it was in there

**Comment by dselman** [comment]
Closing this as implemented, though it does not support inline images. We can open a new story for that if necessary.
