### ISSUE TITLE
Support page refers to Slack channel

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#145]
Need an invite to the Slack channel? Send us an email: info@fabric-composer.org

**Comment by mbwhite** [comment]
Also we still have the slack icon...

**Comment by mbwhite** [comment]
![image](https://cloud.githubusercontent.com/assets/6673453/22830934/46d75226-efa0-11e6-8ebe-c9f1f5a8dd34.png)

**Comment by mbwhite** [comment]
Updates are complete.
