### ISSUE TITLE
Lack of Github authentication causes rate limiting issues

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#153]
See PR #152 for temporary fix.

We do not use any form of Github authentication, and so we are subject to a 60 requests/hour rate limit per IP. This is pretty easy to hit and will be especially bad for users inside a corporate network, for example the workshop users next week.

One thing I noticed is that we appear to be going out to Github on UI startup, even if I don't click on the "Sample switcher" button - so maybe we can at least cut down the number of requests?

**Comment by caroline-church** [comment]
Fixed
