### ISSUE TITLE
404 on docs page - "Connection Profile"

### ISSUE THREAD

**Issue by winslet** [fabric-composer/fabric-composer#156]
Hey, im getting a 404 on one of the docs pages titled "Connection Profile":

![image](https://cloud.githubusercontent.com/assets/13980028/22885333/ce3067a6-f1f0-11e6-97a5-7fe85aefec21.png)

https://fabric-composer.github.io/reference/reference/connectionprofile.html is what it is referencing at the moment, looks like we need to remove one of the "reference" parts from the URL, as this page loads: https://fabric-composer.github.io/reference/connectionprofile.html

Thanks!

**Comment by Jakeeyturner** [comment]
[Will be fixed in this PR](https://github.com/fabric-composer/fabric-composer/pull/129)
