### ISSUE TITLE
Multiple 404s on docs pages - "Application Generator/CLI Add participant/CLI Issue Identity/CLI Revoke Identity/API Docs"

### ISSUE THREAD

**Issue by winslet** [fabric-composer/fabric-composer#157]
Discovered a bunch of 404's, these all seem to be linked to concerto URLs:

![image](https://cloud.githubusercontent.com/assets/13980028/22885535/c67e41b2-f1f1-11e6-9044-c4e40d974269.png)

Not too sure where they're supposed to be pointing right now, but can all be found from these pages: https://fabric-composer.github.io/reference/MeetTheModules.html

Thanks

**Comment by Jakeeyturner** [comment]
[Will be fixed in this PR](https://github.com/fabric-composer/fabric-composer/pull/129)
