### ISSUE TITLE
404 on docs page - "Network Deploy Command"

### ISSUE THREAD

**Issue by winslet** [fabric-composer/fabric-composer#158]
Can be found at the bottom of this page: https://fabric-composer.github.io/concepts/businessnetwork.html

![image](https://cloud.githubusercontent.com/assets/13980028/22885670/601abb48-f1f2-11e6-9cda-a995e16f3f9b.png)

URL currently pointing at: https://fabric-composer.github.io/reference/networkdeploycommand.html not too sure where it is supposed to be.

Thanks

**Comment by Jakeeyturner** [comment]
[Will be fixed in this PR](https://github.com/fabric-composer/fabric-composer/pull/129)
