### ISSUE TITLE
Building docs locally does not use local packages

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#162]
When generating and deploying docs locally, the version of each package in npm is used to generate them, rather than the local version

**Comment by mbwhite** [comment]
The heritage of the documentation scripts is that they were not in the same repository as the code. Hence the docs project had a dependency on the modules to pull down the code - and therefore build them.

This is completely pointless now; so the configuration can be changed. `fabric-composer/site/jsdocs-template/jsdoc.conf' can be modified to instead refer to the code in it's actual location.  Also the dependencies can be removed.

**Comment by mbwhite** [comment]
In order to solve this problem properly moving the site directory into the packages directory so it's under Lerna control I think is the best way to solve this. 

That way the internal dependencies are correctly resolved.

**Comment by mbwhite** [comment]
This has now occurred and the site documentation is now within the main packages repo. This does mean that 'lerna bootstrap' is needed to correctly setup the dependancies so the correct code is documented.
