### ISSUE TITLE
As a contributor I should not be able to inadvertantly change the public API

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#20]
We need to enforce API change tracking on all repos (using lerna?), breaking the build if it is not enabled.

Change tracking is currently only used for the primary API repos. See composer-common for example.

**Comment by samjsmith** [comment]
Thoughts in the room are that the only way to really enforce this is to not allow a contributor who has a PR that changes the public API to merge their own PR.  
We think that there is a mechanism to detect when someone is changing the public API and so we need to link that somehow to the Git rules that enforce the merge of PRs.

**Comment by dselman** [comment]
Changes to public API that are not added to changelog.txt currently break the build (there is a test that the checksum of the public API + version are in changelog.txt). So, I think we have what we need for composer-common -- but this is not enforced on all repos that contain public API (?).

**Comment by samjsmith** [comment]
Ok @dselman we thought that there was a desire to have an enforced review of the PR so that a malicious actor couldn't do it alone.  Our discussion must have taken us down that path somehow!
Can you list which packages in the repo have public APIs please?

**Comment by caroline-church** [comment]
@mbwhite Can this be closed?

**Comment by mbwhite** [comment]
@caroline-church yes I think this can be closed off; we have the code as Dan's mentioned plus the other repos don't really have public APIs as such that can be consumed. They use the public APIs.
