### ISSUE TITLE
Loopback connector not displaying Transactions

### ISSUE THREAD

**Issue by jdockter** [fabric-composer/fabric-composer#200]
When running a loopback server pointed at my running business network I'm unable to see Transactions loaded to the api explorer (http://0.0.0.0:3000/explorer/)

**Comment by samjsmith** [comment]
@jdockter Hey Jon, which business network did you have deployed?

**Comment by jdockter** [comment]
It's my own business network that I have been building.  I got the loopback server to pickup transactions by going into the node_modules under loopback-connector-composer and updating the businessnetworkconnector.js file, under the discoverModelDefinitions function...line 145 ...I had gotten some code from Matthew to add an OR condition ...now it seems to work.

**Comment by samjsmith** [comment]
@jdockter Yeah that code looked odd so I updated it just now. I'm not sure that running a transaction will work just yet though - I don't think it has ever been actually tested.

What HTTP verb would you expect to be able to use to submit it? Initial thoughts are that we should just enable GET (to get the script) and POST (to run it) but it'd be good to get your thoughts.

At the moment, it looks like we need to add some other fields to the LoopBack model to restrict all the APIs that it's generating which needs looking into.

**Comment by jdockter** [comment]
POST make sense as the would allow you to send in the JSON to invoke the transaction.  Would GET give you all the transaction definitions from the business network, like those modeled in the CTO or the actual implementation code from the .js file?

**Comment by dselman** [comment]
We should only expose POST for transactions, which submits a transaction for processing. I'm in two minds as to whether we just need a generic `/submit` endpoint, or whether the endpoints should be typed and per-transaction type. The former seems easier for the application developer to use (they can submit any transaction to a generic endpoint), while the later gives type-safety and the ability to test within Swagger UI.

**Comment by jdockter** [comment]
My two cents would be type-safety

**Comment by samjsmith** [comment]
I've chatted with some folks who have a good grip on the loopback connector status and unfortunately, restricting the swagger API that's generated isn't possible using the JSON data. See this doc here: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html 

So we either wait until it is implemented or add in some capability in the loopback connector boot script (which could also be built into the composer-rest-server package that uses the javascript API to do this programmatically.

**Comment by sstone1** [comment]
> So we either wait until it is implemented or add in some capability in the loopback connector boot script (which could also be built into the composer-rest-server package that uses the javascript API to do this programmatically.

FYI, I have this working locally.

**Comment by samjsmith** [comment]
Great stuff Simon - get it checked in!

**Comment by sstone1** [comment]
The latest version of `composer-rest-server` includes changes that limit the set of generated REST APIs. The REST APIs are now:

GET /assetType - get all the instances of asset type
POST /assetType - create a new instance of asset type
GET /assetType/:id - get the specified instance of asset type
HEAD /assetType/:id - check to see if the specified instance of asset type exists
PUT /assetType/:id - update the specified instance of asset type
DELETE /assetType/:id - delete the specified instance of asset type

GET /participantType - get all the instances of participant type
POST /participantType - create a new instance of participant type
GET /participantType/:id - get the specified instance of participant type
HEAD /participantType/:id - check to see if the specified instance of participant type exists
PUT /participantType/:id - update the specified instance of participant type
DELETE /participantType/:id - delete the specified instance of participant type

POST /transactionType - submit a new instance of transaction type
