### ISSUE TITLE
As a contributor I can contribute code to the new Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#204]
This story consists of bootstrapping development of the new Composer Playground, based on the lo-fi and hi-fi designs from IBM Design.

- [x] Create a new npm package composer-playground (as a peer of the existing Playground)
- [x] Create the skeleton for the Angular2 application (or port existing)
- [x] Define new CSS etc
- [ ] Update build to push composer-playground docker image (similar to https://hub.docker.com/r/fabriccomposer/composer-ui/)

**Comment by sstone1** [comment]
We need finer grained stories for porting the existing functionality from Composer-UI.

**Comment by caroline-church** [comment]
Closing as we have stories now for the work
