### ISSUE TITLE
As a contributor I want to publish Atom plugins to their marketplaces

### ISSUE THREAD

**Issue by xufengli** [fabric-composer/fabric-composer#210]
When the Atom code is modified under tools or the VSCode plugin is modified we want the plugins to be published to their respective plugin marketplaces for easy integration into the editor.

This is an enabler for story #31

**Comment by xufengli** [comment]
We need two icons for Atom and VSCode plugins on their marketplaces.

**Comment by xufengli** [comment]
@dselman We need to create an account in VSCode Marketplace in order to publish our plugin.

**Comment by dselman** [comment]
https://code.visualstudio.com/Docs/extensions/install-extension

**Comment by xufengli** [comment]
When I publish Atom plugin with this: apm publish I have got this error:
Package must be in a Git repository before publishing: https://help.github.com/articles/create-a-repo.
The reason is that our repository is under the tools root directory, but the package is at one level below the tools directory. 
We have either of these solutions:
1. Use git submodule  to create a nested structure of the git modules 
2. Have multiple git repository for each plugins

With solution 2 we still face submodule issues for VScode as this have client and server modules.

**Comment by dselman** [comment]
Please contact @Jakeeyturner or @AnastasiaPaterson regarding the VSCode account -- they are guardians of our corporate accounts.

**Comment by bestbeforetoday** [comment]
Cut this down to just cover Atom, with #338 for VSCode.

**Comment by xufengli** [comment]
In this case, we can close this story.
