### ISSUE TITLE
Need docs for the Loopback REST Server

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#215]
We need to add docs to tasks and reference that describe how to use the new Loopback REST Server and refactor this:
https://fabric-composer.github.io/start/getting-started-rest-api.html

**Comment by samjsmith** [comment]
This is one of the items listed in #42 so I'll mark it as a duplicate and close this one since the other issue is the containing story. 
We need to work out how we're going to split things up from here on in :)
