### ISSUE TITLE
As a user, I can submit a Transaction via the Fabric Composer Playground

### ISSUE THREAD

**Issue by EdMoffatt** [fabric-composer/fabric-composer#219]
"Submit Transaction" button is available in the left-hand panel (so usable on any panel in the Test section of the UI).

When clicked, we should contact the ledger to see if we can populate suggestions for any fields that reference artefacts from the model e.g. get the current list of Assets of the type that this transaction acts on.

The user can complete the transaction submission without the suggestions, either by filling out the fields or editing the JSON.  As with other Create modals, we'd only provide the JSON option if this type is somehow too complex to provide a form for!

When the "populate suggestions" completes, any fields that are based off the contents of the ledger will have dropdowns added to them to select from a list of available artefacts, and if the user starts typing, they will get suggestions.

Values not from the list of suggestions can still be input e.g. for testing of error handling.

We expect that if in web-browser connection profile, the "populate suggestions" should be instantaneous, so we may not even need the "getting them" state.

Low-fi designs for this are available, pages 35-42 in https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

**Comment by sstone1** [comment]
This needs to be split into 2 stories, P1 story is to get the JSON submission working, P2 is web form generation.

**Comment by samjsmith** [comment]
@sstone1 @EdMoffatt 
I've converted this to an Epic and created 4 sub-issues. 3 are P1 and give the basic JSON view and the the other is for the 'smart forms' view which I think is outside the scope of this playback.  Let me know if you think I've missed anything chaps :)

**Comment by EdMoffatt** [comment]
The remaining work on this one is to add in the form-input version of Transaction submission.  Knocking the priority down to acknowledge it's not top of our priority right now!
