### ISSUE TITLE
As a user I should have documentation for how to run the application generators

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#22]
There are currently no docs for `yo fabric-composer` under tasks or references.

**Comment by dselman** [comment]
We have this: https://fabric-composer.github.io/tasks/genapp.html

But it doesn't discuss the Angular2 generator.

**Comment by Jakeeyturner** [comment]
Updated https://fabric-composer.github.io/tasks/genapp.html with some Angular2 generator instructions.

**Comment by dselman** [comment]
The page has formatting issues.

**Comment by Jakeeyturner** [comment]
[Fixed the formatting, I'll close this again unless any other changes need to be added.](https://fabric-composer.github.io/tasks/genapp.html)
