### ISSUE TITLE
Playground SVG's won't load on Firefox

### ISSUE THREAD

**Issue by Jakeeyturner** [fabric-composer/fabric-composer#221]
Just tested the playground in Firefox and SVG images don't appear to render at all.
They seem to render in Chrome, but it's worth testing other browsers as well, e.g. Internet Explorer, Safari, etc.

**Comment by dselman** [comment]
I can confirm they don't render on Firefox on the Mac, but Safari and Chrome both work

**Comment by winslet** [comment]
hmmm not sure im the best to work out whats going on here. Sounds like some cross browser implementation of SVG's isnt supported in FF. @Jakeeyturner how were the SVG's embedded is there code somewhere I can look at?

**Comment by Jakeeyturner** [comment]
@caroline-church Seems to have fixed this, and I imagine it'll be merged in a PR soon!
