### ISSUE TITLE
UnhandledPromiseRejectionWarning in the loopback connector when filter is added to query string

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#227]
When I try to access `http://localhost:3000/api/com.ibm.concerto.mozart.Animal?filter={%22resolve%22:true}` when running a loopback server using the loopback connector, I see the error 
```
(node:10087) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
```
I see the same error regardless of the property name in the filter object

**Comment by samjsmith** [comment]
@14gracel does it work if you use the {'include':'resolve'} filter?

**Comment by 14gracel** [comment]
@samjsmith Still getting the same error on with the animalTracking network. Ill do some more digging and check its not an application issue
