### ISSUE TITLE
As a user I should be able to pull a Composer-UI server from docker hub

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#23]
The build should create a complete Composer Playground server configuration and push to DockerHub. Currently creating the docker image from composer-ui is difficult/broken.

The downloaded image should allow the user to use either the web or HL connection profile.

**Comment by sstone1** [comment]
Closing as complete, and also as this is really superseded by issue #132.
We are pushing `composer-ui` images to Docker Hub on a regular basis, and the installation instructions are documented here: https://fabric-composer.github.io/start/getting-started-playground.html
We have multiple successful reports of users pulling and using these images.
