### ISSUE TITLE
Serializer.toJSON only accepts instances of Resource error when using Loopback connector

### ISSUE THREAD

**Issue by samjsmith** [fabric-composer/fabric-composer#238]
You get this error when you specify the {"include" : "resolve"} filter on the loopback connector.

It seems that the composer API returns JSON data from the resolve/resolveAll functions but returns Resource instances from the get/getAll APIs which means that you then need to run a Serializer.toJSON function to return JSON data to the client.

I'll make the connector deal with now this but I wonder if the composer API should be more consistent on this. One for @dselman or @sstone1 to think about.

**Comment by dselman** [comment]
Yes, the results of calling resolve is JSON data, not instances of Resource, because when relationships are resolved the data is no longer schema valid with respect to the model.

This is by design.

**Comment by samjsmith** [comment]
I'm not sure I completely understand what you're getting at here @dselman but if it's by design then that's fine and you can explain it to me over a cup of tea or coffee sometime :)
