### ISSUE TITLE
As a user or contributor I have issue templates for helping me provide required information

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#242]
We need GitHub templates for issues and pull requests.

Free-form text is not helpful in generating issues that can be picked up and worked on by the wider community. For example, issues should have the following information:

- What did you do?
- What OS/package versions/browser/etc did you use?
- What happened, and why was it unexpected?
- Can you explain what is causing the issue?

Issues should also have reproduce information (short scripts, UI steps, etc).

Pull requests need the same treatment. As a maintainer trying to figure out if they should merge a pull request, that pull request should have:

- A link to the issue/user story that the pull request relates to
- How to recreate the problem without the fix
- Design of the fix
- How to prove that the fix works
- Automated tests that prove the fix keeps on working

Some of this might just be linking to information in the issue, and some of it might just be a checkbox to say "I have read the contributing guidelines, and have followed all the steps".

I think there's some good discussion to be had as a team about what we'd like to see in these templates. We need to make sure we get the right amount of information without making the process too painful for the users.

**Comment by mbwhite** [comment]
c.f. http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by mbwhite** [comment]
@sstone1 I'd added a issue template end last week under other changes... and I've a pull request as well.   Want to leave this open for wider discussion or see how the templates get used?

**Comment by sstone1** [comment]
@mbwhite I saw the new issue templates, I'm a big fan 👍
