### ISSUE TITLE
As a user I can easily communicate with the contributors

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#25]
The slack sign up process needs to be clear.

**Comment by mbwhite** [comment]
# Updates

Slack is not being used; as the Hyperledger project has moved to RocketChat. So signup process is per the standard Linux Foundation rules.  https://hub.docker.com/u/fabriccomposer/

## Channels
### Code
Modules are published on npmjs and Docker images are on DockerHub
- https://www.npmjs.com/search?q=fabric-composer
- https://hub.docker.com/u/fabriccomposer/

Github repo for the code and contributor information (in READMEs)
- https://github.com/fabric-composer

### Community Discussion
Rocket Chat https://hub.docker.com/u/fabriccomposer/

Mailing list - still be discussed and not yet created.

### Q&A
Stackoverflow http://stackoverflow.com/tags/fabric-composer

## Process
Weekly point person to ensure that nothing gets dropped unanswered etc. 

## Introductory Material
Slideshare: https://www.slideshare.net/SimonStone8/fabric-composer-london-hyperledger-meetup-march-2017?qid=3d347caf-3bd4-48be-98d2-7d1cc296f0bd&v=&b=&from_search=1


---
# Missing things

- Weekly ' this week in fabric-composer' suggested
- Package of introductory material - presentations PPT - and demos required.
- Update the contributor information in GitHub

**Comment by mbwhite** [comment]
Contributor information has been updated; worth reviewing again:

**Comment by dselman** [comment]
Closing this as I think we've made great progress.
