### ISSUE TITLE
Package.json has an inconsistent roundtrip

### ISSUE THREAD

**Issue by Jakeeyturner** [fabric-composer/fabric-composer#250]
A business network archive file contains a package.json file which has a name, version, description and additional data such as dependencies, author, scripts, keywords, github repository, etc.

When a business network archive is deployed, the 'fromArchive' function takes the archive file and creates a business network definition using the name, version and description. 

If we were then to export the business network definition using the 'toArchive' function, we'd then create a business network archive file which is inconsistent with the business network archive file we originally deployed the network with.

This is because the business network definition does not hold the additional package.json metadata.

The cause of the problem can be seen here: https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-common/lib/businessnetworkdefinition.js#L134L148

**Comment by dselman** [comment]
The source package.json file is now available using the BusinessNetworkDefinition.getMetadata().getPackageJson() API.
