### ISSUE TITLE
As a user I should be able to use a README.md to describes a business network definition

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#251]
A user can place a README.md in the root of their business network archive. This file will be used in the Playground to guide users in how to interact with the business network, or explain how it works.

Implementation nodes:

- README.md is now availble from businessNetworkDefinition.getBusinessNetworkMetadata().getREADME()

**Comment by nklincoln** [comment]
If we permit a user to place one and only one README.md file in the root of their BNA, and images within a ./images directory, then:

- BusinessNetworkDefinition class can be extended to extract and store this information in a new (extensible) Metadata class
- Create a new API on the BusinessNetworkDefiniton class to enable retrieval of the Metadata information (in this case the README.md text or a byte[] relating to a README image)

**Comment by dselman** [comment]
PR #361
