### ISSUE TITLE
Loopback REST API not honoring optional field

### ISSUE THREAD

**Issue by jdockter** [fabric-composer/fabric-composer#253]
I have an asset with an optional array of transactions.  

asset TimeSheetListing identified by tsId {
  o String tsId
  --> PurchaseOrder po
  o LogHours[] logHours optional
}

When I go to create that asset via the API explorer I get an error saying missing required field from the optional logHours.

` "message": "Instance ibm.procurement.laborNetwork.LogHours#undefined missing required field trxId",
    "stack": "ValidationException: Instance ibm.procurement.laborNetwork.LogHours#undefined missing required field trxId\n    at Function.reportMissingRequiredProperty (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:474:15)\n    at ResourceValidator.visitClassDeclaration (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:161:39)\n    at ResourceValidator.visit (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:64:25)\n    at TransactionDeclaration.accept (/home/jdockter/loopback-server/node_modules/composer-common/lib/introspect/classdeclaration.js:63:24)\n    at ResourceValidator.checkItem (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:328:30)\n    at ResourceValidator.checkArray (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:255:18)\n    at ResourceValidator.visitField (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:201:22)\n    at ResourceValidator.visit (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:68:25)\n    at Field.accept (/home/jdockter/loopback-server/node_modules/composer-common/lib/introspect/property.js:48:24)\n    at ResourceValidator.visitClassDeclaration (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:157:26)\n    at ResourceValidator.visit (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer/resourcevalidator.js:64:25)\n    at AssetDeclaration.accept (/home/jdockter/loopback-server/node_modules/composer-common/lib/introspect/classdeclaration.js:63:24)\n    at Serializer.toJSON (/home/jdockter/loopback-server/node_modules/composer-common/lib/serializer.js:89:30)\n    at AssetRegistry.add (/home/jdockter/loopback-server/node_modules/composer-client/lib/registry.js:194:50)\n    at businessNetworkConnection.getAssetRegistry.then (/home/jdockter/loopback-server/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:407:50)\n    at process._tickDomainCallback (internal/process/next_tick.js:129:7)" `

**Comment by dselman** [comment]
https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
Line 385 sets the optional field in the JSON Schema.

**Comment by jdockter** [comment]
Here is the JSON I use...po 12345 is valid

{
  "tsId": "003",
  "po": "12345",
  "logHours": [
    {}
  ]
}

**Comment by dselman** [comment]
So the logHours array contains 1 entry, which is an Object, and the Object has no fields... So this is legitimately invalid with respect to the model.
