### ISSUE TITLE
TypeError: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by jdockter** [fabric-composer/fabric-composer#256]
When trying to create a new bna file through `composer archive create --inputDir .` I was getting the error

TypeError: Cannot read property 'trim' of null

I loaded my model and script to http://fabric-composer.mybluemix.net/#/editor and also got the same error.  I stripped out all the code and got to the point that the error was from the statement `@param  {ibm.procurement.laborNetwork.LogHours} logHours`...if I added any text after logHours, for example '@param  {ibm.procurement.laborNetwork.LogHours} logHours -' the parsing error went away.  Do I always need to have a comment after the variable in param?

**Comment by 14gracel** [comment]
You no longer need to as of commit 93b0f8d
