### ISSUE TITLE
Composer-UI doesn't display samples to import

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#261]
v0.4.4.4 is deployed here:
http://fabric-composer.mybluemix.net

It is not currently displaying any of the samples to import or any error message. Is this because of the GitHub rate limit? Can we at least print something so people know what is going on?

**Comment by caroline-church** [comment]
It isn't the rate limit. It is because the `composer-connector-server` needs to be running too. We need this to be deployed to bluemix too

**Comment by caroline-church** [comment]
This will be fixed by fabric-composer/fabric-composer#266

**Comment by dselman** [comment]
Thanks to you and @sstone1. It's obviously critical to bring the samples back online ASAP.

**Comment by sstone1** [comment]
This won't be fixed by #266; #266 only separates the connector server and playground REST APIs.
I'll use this issue to get all of the APIs running on Bluemix as a CF application.
