### ISSUE TITLE
As a devloper a support for writing test suites to support test driven development

### ISSUE THREAD

**Issue by AntCole** [fabric-composer/fabric-composer#264]
Addition by Paul Sitoh [paul.sitoh@uk.ibm.com]:

In the Garage we do Test Driven Development, where we write test first then implementation. It is unsure how this would work with composer.

We also do other form of automated testing (unit, integration, smoke and UI testing) and these are typically integrated as part of Continuous Integration (CI) and Continuous Delivery (CD) and again not sure how this would work with composer.

**Comment by sstone1** [comment]
We already support unit testing of transaction processor functions in Node.js by virtue of our embedded runtime. For example: https://github.com/fabric-composer/sample-networks/blob/master/packages/DigitalProperty-Network/test/DigitalLandTitle.js

These unit tests can be integrated into npm by the standard mechanisms (running mocha) and so also easily integrated into CI systems such as Travis. Integration/UI/end-to-end/system/whatever testing with Composer can be set up using any standard testing methodology, I don't think we need to do anything special to support that.

**Comment by dselman** [comment]
Here is the unit test for the CarAuction:
https://github.com/fabric-composer/sample-networks/blob/master/packages/CarAuction-Network/test/CarAuction.js
