### ISSUE TITLE
Separate the connector server and the REST API to support the playground

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#266]
The `composer-connector-server` is starting to get a few additions for things like GitHub OAuth support; this needs to stop.

The connector server is the server side of the proxy connector, which allows the Composer client/admin APIs running in a web browser to access the HLF connectors that cannot be run in a browser (as gRPC is a native dependency). The connector server uses socket.io to allow for bidirectional communication between the proxy connector and connector server which is required in order to support events when we get there.

The connector server should stay solely as a socket.io server that supports the proxy connector. It may be useful outside of the playground, for example if someone wants to enable similar web browser and connection profile options for their business network built on top of Composer.

My opinion is that the REST API functionality to support the playground should be moved into a new module, or into the `composer-playground` module itself. I think from memory a separate module might be easier? The connector server can then be "mounted" into the REST API served by the playground, as the socket.io APIs allow you to give it an Express application.

**Comment by caroline-church** [comment]
Ok let's create a new module for the rest api stuff.

**Comment by caroline-church** [comment]
Can i give this to you to implement please?

**Comment by sstone1** [comment]
@caroline-church I've pulled out the playground specific APIs into a new `composer-playground-api` module and changed them to REST APIs hosted in Express. When that Express server starts, it also loads in the `composer-connector-server` APIs.

The new REST API routes are here; over to you to update as you see fit and also change the UI to call the new APIs instead of using socket.io requests:
https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-playground-api/routes/github.js
https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-playground-api/test/github.js

I'll tackle the Bluemix stuff in a different issue.

**Comment by sstone1** [comment]
We may also want to consider renaming `composer-playground` to `composer-playground-ui` so it's clear what module does what.
