### ISSUE TITLE
Runtime AssetRegistry and ParticipantRegisty exists method

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#268]
It would be useful to add the Registry.exists method to the runtime Asset and Participant registry implementations:
https://fabric-composer.github.io/jsdoc/module-composer-client.Registry.html#exists__anchor

**Comment by dselman** [comment]
Context is a sample I am creating that needs a transaction that either creates an asset, or updates the asset if it already exists.

**Comment by dselman** [comment]
Reported on RocketChat.

**Comment by sstone1** [comment]
Fixed in PR #573. Will be in the next released version.
