### ISSUE TITLE
Issue getting sample to run

### ISSUE THREAD

**Issue by joshm** [fabric-composer/fabric-composer#269]
When I run npm install with node v6.10 and npm 4.x I get the below error, this is during the compose archive create:

 composer archive create --sourceType module --sourceName digitalproperty-network --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d

Creating Business Network Archive[object Object]
undefined
Unable to locate the npm module specified
TypeError: Cannot read property 'length' of undefined
Command failed.

Any ideas?

**Comment by rameshthoomu** [comment]
@joshm Observed the same error while executing `npm install` from here https://fabric-composer.github.io/start/quickstart.html but this issue got resolved for me after executing step 3, 4 and 5 from this doc https://fabric-composer.github.io/start/quickstart.html manually in CLI.

**Comment by dselman** [comment]
Just fixed this by updating package.json for the gettingstarted example.
