### ISSUE TITLE
Composer-UI Car Auction JSON sample data update

### ISSUE THREAD

**Issue by AntCole** [fabric-composer/fabric-composer#293]
In the composer UI Car Auction Sample, when adding a transaction to org.acme.vehicle.auction.VehicleListing it auto generates a number of transactions with random data inserted. 

Please make some of this data not-so-random so the JSON does not need to be completely altered or remove all offers array for the demo to work.

{
  "$class": "org.acme.vehicle.auction.VehicleListing",
  **"listingId": "listingId:1467",         //use this listingId throughout this transaction**
  **"reservePrice": 217.328,             //use 2 decimal places?**
  "description": "jar share",
  **"state": "RESERVE_NOT_MET",     //Default to use "FOR_SALE" rather than random allocation**
  "offers": [
    {
      "$class": "org.acme.vehicle.auction.Offer",
      "transactionId": "transactionId:7941",
      "bidPrice": 171.901,
      **"listing": "listingId:3571",        //default use the same listingId as above**
      **"member": "email:2710",         //Randomly pick one of the participant emails or add 2/3 starter participants and use those emails in these fields.**
      "timestamp": "2006-12-01T23:39:13.969Z"
    },
    {
      "$class": "org.acme.vehicle.auction.Offer",
      "transactionId": "transactionId:0367",
      "bidPrice": 39.755,
      "listing": "listingId:5152",
      "member": "email:8069",
      "timestamp": "2016-08-31T10:03:59.640Z"
    },
    {
      "$class": "org.acme.vehicle.auction.Offer",
      "transactionId": "transactionId:7599",
      "bidPrice": 88.531,
      "listing": "listingId:8437",
      "member": "email:5638",
      "timestamp": "2005-06-14T10:39:36.005Z"
    }
  ],
  **"vehicle": "vin:5881"        //Put 'vehicle' above 'offers' - Easier for user to see this field
                                            //Default Vin to same default used for org.acme.vehicle.auction.Vehicle sample? or pull the info for a random asset listed in org.acme.vehicle.auction.Vehicle?**
}

**Comment by dselman** [comment]
Some of this is taken into account in the new designs for playground.

**Comment by caroline-church** [comment]
going to be superseeded by simple view
