### ISSUE TITLE
Add UI URL to top of QuickStart Page

### ISSUE THREAD

**Issue by AntCole** [fabric-composer/fabric-composer#294]
The quickest way for someone to use Composer is to play with the bluemix web-UI but this is not shown in the quickstart

Please add the bluemix URL (http://fabric-composer.mybluemix.net) to the top of the quickstart page (https://fabric-composer.github.io/start/quickstart.html) to inform potential users of the quickest method to play/test the system, then they can then install fully when ready.

Noted this may not be a fully advertised route yet so can park this until the new UI is ready if wanted.

**Comment by dselman** [comment]
We will add this once we get the new playground deployed.
