### ISSUE TITLE
UX Review w/b 27Feb - Snag List

### ISSUE THREAD

**Issue by mbwhite** [fabric-composer/fabric-composer#296]
(based on draft document at https://github.com/mbwhite/documents/blob/master/WeeklyUXValidation.md)

**Comment by mbwhite** [comment]
# Quickstart

- Ubuntu 16? 
- Node 4 - change
- nvm no mention
- git no mention

or greater needs to be added if applicable (but not for node 7)

Empahize the composer install  & and check in the npm install that it exists and version.

Better examples in the `composer` cli.

Remove the todo and commented out code in the running scripts

remove the .bna file from the github repo

details of the business network that is deployed is done before the NPM tree.. so you miss them.. is there a post install bit that could do that instead?

remove undefined.

? Should this be a shrink wrapped sample.

Where to go after the getting started??

**Comment by mbwhite** [comment]
# Command line
- Need to update the 1st para to make it easy to read if you have come from the quick start
- Name of the filename is different 
- Needs to be clear that HLF needs to be up and working.
- There are 2 working directories here that need to be made clear... when updating the tran and running the submit tran, there are 2 directories
- No output shown to prove anything has happened.

**Comment by mbwhite** [comment]
# Loopback
- the cd .. - from where  to where?
- new file should be created more automatically.
- get rid of WARNING: No configurations found in configuration directory:/home/matthew/loopback-server/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

Transactions are working here.  - no where to go next.

**Comment by mbwhite** [comment]
Developer routes to creating your own network are unclear. Need to clearing document these for people building their own networks. Also link with the yeoman generator

**Comment by mbwhite** [comment]
# Testing Gaps
UT = unit testing ST = system testing end-end  ET = exploratory human testing 
X = required/update
S  = sufficient

Component        |  UT   | ST   | 
--------------   | ----- | ---- | 
Samples          | X     | X    | 
Getting Started  | X     | X    |   
Loopback         | S     | X    | 
CLI              | S     | X    | 
Playground REST  | S     | S    |
Composer UI      | X     | X    |
Client/Admin API | S     | S    | 
Runtime          | S     | S    |
Generators       | X     | X    |
Go runtime       | X     | S    |
HLConnector      | S     | S    |
WebRuntime       | S     | S    |
Connector Proxy  | X     | X    |
EmbeddedRuntime  | S     | S    |

**Comment by caroline-church** [comment]
@mbwhite Can we create specific issues for this or can we just close this?

**Comment by mbwhite** [comment]
Issue https://github.com/fabric-composer/fabric-composer/issues/449 was created for the testing additions; 

The checklist for the testing is in the contrib directory.

The website issues have been handled or are being handled as part of Ed's general updates
