### ISSUE TITLE
Error loading components when Composer UI local storage values are used

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#304]
Cannot see any components in the editor window when I have old local storage values left over from composer-ui

**Comment by dselman** [comment]
Related to #381

**Comment by Jakeeyturner** [comment]
![screenshot from 2017-03-10 15-12-40](https://cloud.githubusercontent.com/assets/10009752/23800642/17888c72-05a5-11e7-98bb-c77b92cd5f42.png)

If a user has items in their local storage which isn't compatible with the running playground, then we'll need to alert them of this problem and clear the data out for them.

I'll need some design assistance for this modal which informs them, then clears their local storage.
