### ISSUE TITLE
Make the Swagger more appropriate for Java client generation.

### ISSUE THREAD

**Issue by gcharters** [fabric-composer/fabric-composer#307]
I just tried to generate a Java client based on the vehicle auction sample Swagger.  There are two issues I can see so far that make the results a bit challenging to use:
1. The class names are namespace qualified so don't look great.  For example:
public class OrgAcmeVehicleAuctionVehicleListing {
2.  The method names are derived from the Swagger operationIds which in many cases are very long.  A particularly bad example is: 
public File orgAcmeVehicleAuctionVehicleListingCreateChangeStreamGetOrgAcmeVehicleAuctionVehicleListingChangeStream(String options) throws ApiException {

I'm using the JAX-RS client generation tools in the WebSphere Developer Tools, but I believe these are based on these Swagger tools: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java .

**Comment by dselman** [comment]
The namespaces are included to prevent collisions between types with the same short name but coming from different namespaces. Given that this will likely be rare (certainly for small/sample projects) perhaps we should change this to:

1. Only add the namespace if we detect a collision.
2. Add a postfix index if we detect a collision
3. Error if we detect a collision, but provide the ability to turn on namespaces as an option

Thoughts? Other options?

**Comment by mbwhite** [comment]
One issue is that we've not yet seen a complex enough model to be able to reason based on real use case.  The overall route might need to be changed for conflicting types - I'd be tempted to go for option3.

That would seem to protect freedom of movement. 

It would also make consumption with say http://unirest.io and http://www.baeldung.com/rest-template simpler to have a more consumable name.

**Comment by sstone1** [comment]
@gcharters I have made some changes to `composer-rest-server`, please can you try them out?
The command now takes a `-N` option, which can have values of `always`, `required`, and `never`.
The behaviour is as follows:

- `always` always generate REST APIs with namespaces, this is the default
- `required` only generate REST APIs with namespaces if a collision between type names is detected
- `never` never generate REST APIs with namespaces, and throw an error if a collision between type names is detected

**Comment by gcharters** [comment]
@sstone1 - thanks.  I'll take a look at the end of the week (I need to keep my demo working for now).  Is there a default?  I'm hoping if there is, it's "required" or "never" :)

**Comment by gcharters** [comment]
@sstone1 - i've given this a try and it's a vast improvement.  I feel a little uncomfortable that the API can change depending on the deployment option, but unless there's something we're missing around Swagger API design, I think this is the best way forward.
