### ISSUE TITLE
Cannot specify certain characters for instance identifiers in ACL rules

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#310]
I am trying to write a rule for a particular participant, who has the identifier `loopback@email.com`.
I want to write the following rule, as per the documentation:

`Member | org.acme.vehicle.auction | CREATE | org.acme.vehicle.auction.Member#loopback@email.com | (true) | ALLOW | Allow the Loopback connector create access`

However I get an error: `Error: Expected "/*", ":", "|" or whitespace but "@" found. Line 8 column 86`
I have to write the following rule instead:

`Member | org.acme.vehicle.auction | CREATE | org.acme.vehicle.auction.Member:u | (u.getIdentifier() === 'loopback@email.com') | ALLOW | Allow the Loopback connector create access`

**Comment by dselman** [comment]
The text between `(` and `(` is defined as a Javascript `if` expression in the parser. So, anything that is valid for a JS `if` should work there.

**Comment by dselman** [comment]
Fixed
