### ISSUE TITLE
Angular generator hangs after printing Complete

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#320]
Steps to reproduce:
1. Install 0.4.5
2. Run the gettingstarted
3. Install the Angular generator as described here: https://fabric-composer.github.io/tasks/genapp.html
4. Run the generator against the digitialproperty-network
5. The process never exists

**Comment by dselman** [comment]
Workaround is to just CTRL-C the process, then cd into the generated app directory, then
`ng serve`

The app is now running on http://localhost:4200

**Comment by Jakeeyturner** [comment]
[Fixed in PR here](https://github.com/fabric-composer/fabric-composer/pull/358)
