### ISSUE TITLE
Java based generated code from Swagger documentation throws exception when retrieving assets

### ISSUE THREAD

**Issue by davidkel** [fabric-composer/fabric-composer#329]
In the case of Java generated code from a swagger document, it is very ridged about the data flow matching exactly to what is specified and throws an error if it doesn't.

In the case of asset retrieval the loopback connector returns the information exactly as received which includes the "$class" property. However the swagger documentation is generated from the model itself (which doesn't define the $class property as this is an internal property used by composer and isn't a part of the model definition) so doesn't list this property. 

Java code generated is not expecting this property and when it is returned because it doesn't conform throws an exception

**Comment by davidkel** [comment]
the swagger docs for the loopback connector now list the $class property as optional

**Comment by gcharters** [comment]
Hi @davidkel - has this been tested with a Java client?  I'll give it a try at the end of this week/early next week, but IIRC, I tried to manually add $class to the Swagger and it generated code with a getClass() method that clashed with Object.getClass() so wouldn't compile.

**Comment by davidkel** [comment]
@gcharters I've generated a java client quickly using the swagger code generator and that generated code that handled the $class ok, but that's as far as I have tried.

**Comment by gcharters** [comment]
Hi @davidkel - what did your Java code look like for handling $class?  I've just done this with the JAX-RS tools in WDT and it gives me code that won't compile.  For example, the following method clashes with Object.getClass().

  @ApiModelProperty(value = "The class identifier for this type")
  @JsonProperty("$class")
  public String getClass() {
    return _class;
  }
  public void setClass(String _class) {
    this._class = _class;
  }
