### ISSUE TITLE
Text only About page for Composer Playground

### ISSUE THREAD

**Issue by bestbeforetoday** [fabric-composer/fabric-composer#333]
As a user, I want to see an **About** page when I start using Fabric Composer Playground
so that I have detailed information immediately available on how the tool works

Staged approach will start with a text-only version of the About page.

**Comment by EdProsser** [comment]
@caroline-church If you'd like I can proof the text from an ID perspective, obviously I don't understand the technical stuff behind the playground yet. ^^

**Comment by caroline-church** [comment]
@edProsser that would be really good. We need to proof the text on all the samples. The about page shows the readme for each of the samples

**Comment by EdProsser** [comment]
@caroline-church When there's text ready to be proofed, let me know and I'll have a read and get it back to you.

**Comment by caroline-church** [comment]
done so closing
