### ISSUE TITLE
Empty string Id permitted in json definition when generating/validating a resource (Asset/Participant)

### ISSUE THREAD

**Issue by nklincoln** [fabric-composer/fabric-composer#341]
When building a resource (Asset/Participant/Transaction) from a JSON definition, it is possible to input valid json that contains an empty string for UUID 

by example of the sample asset:

{
  "$class" : "org.acme.biznet.SampleParticipant",
  "participantId" : "",
  "firstName" : "",
  "lastName" : ""
}

The above is valid json, but the participantId should not be permitted to be an empty string. From the above json definition, we can generate a resource from the serialiser, validate it,  and subsequently add it to a registry. This is then present in the registry with an empty string id, which does respect prevention of duplicate id items (another empty string)

**Comment by dselman** [comment]
Fixed and unit test added.
