### ISSUE TITLE
Business network undeploy appears to do nothing on the runtime

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#345]
We call the following runtime function from `HFCConnection.undeploy`:

`return HFCUtil.invokeChainCode(securityContext, 'undeploy', [businessNetworkIdentifier]);`

It would be nice if the function was called  `undeployBusinessNetwork` to tie in with the related runtime functions. Also, the argument is not needed here, we know what the business network identifier is.

I don't think the code in the runtime actually does anything.
I can't see where it writes to the world state (comments in-line):

```
return dataService.getCollection('$sysdata')
           .then((sysdata) => {

               // set flag in the sysdata to say that this has been undeployed
               sysdata.undeployed=true; <-- this persists nothing in the world state
               // Validate the business network archive and store it.
               return sysdata.get('businessnetwork');
           })
          .then((object)=> {
              let businessNetworkArchive = Buffer.from(object.data, 'base64');
              return BusinessNetworkDefinition.fromArchive(businessNetworkArchive);}) <-- why are we parsing it?
          .then((businessNetworkDefinition) => {
               // Reinitialize the context to reload the business network. <-- why, it hasn't changed!
              LOG.debug(method, businessNetworkDefinition.getIdentifier()+' has been undeployed');
              LOG.exit(method);
          });
```

It needs to be changed to:
1. Get the "$sysdata" collection
2. Get the "businessnetwork" object from the "$sysdata" collection
3. Add a undeployed flag to the "businessnetwork" object
4. Update the "businessnetwork" object in the "$sysdata" collection so it gets persisted

Context.loadBusinessNetworkDefinition() also needs updating to reflect these changes.
Unit tests and system tests should also be added.

This functionality will disappear when we get chaincode stop/delete in v1.0+ but until that appears this bug report is still valid and needs fixing (or we could just remove the runtime code and make the undeploy client side only until that happens).

**Comment by 14gracel** [comment]
Any decisions about what is happening here? Make it client side only and wait for v1, or implement the changes?
