### ISSUE TITLE
As a user I should be able to load sample networks from GitHub into Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#35]
Currently the sample networks are hardcoded into Composer. These should be loaded from GitHub so they are easier to maintain.

**Comment by dselman** [comment]
https://github.com/philschatz/octokat.js

**Comment by EdMoffatt** [comment]
See pages 2-6 in the latest low-fis: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

Hi-fis to be provided by Sam!

**Comment by winslet** [comment]
Hifi flow below: 

#### User selects "Import/Replace" from Define tab

![Fabric Composer Playground Define 2 Copy 13](http://static.gitscout.com/9c20fa05f65f36f7489a150b8c227e2a37694ac42751062a63869542b490d181.png)

#### Modal appears, giving user option to select existing networks or upload their own.

![Fabric Composer Playground Define 2 Copy 24](http://static.gitscout.com/7fa7b14b54950e035ca6b6323a137bfcbe278039ef78a25a1e103b91f818b4bd.png)

#### Flow 1: User uploads their own business network

TBC

#### Flow 2: User selects pre-existing sample network and clicks deploy

![Fabric Composer Playground Define 2 Copy 25](http://static.gitscout.com/708b7d344a499c9593b7e1fddadaf240b769b0ed3d76fa231b24dc1edaf874e5.png)

(note: the spinner on the button appears during deployment then the modal disappears and the user is taken to the define tab showing the new sample network). 

Marketch of the above screens:

[Upload_Business_Network_SW_1.zip](http://static.gitscout.com/2ce7f3287394b01f499377c868fceecfd11e4a3947b79bb416a8d8e4223d7f0c.zip)

**Comment by caroline-church** [comment]
Done
