### ISSUE TITLE
Remove Mentions of Fabric Composer's original name

### ISSUE THREAD

**Issue by mbwhite** [fabric-composer/fabric-composer#366]
## Context
The code contains references to the previous name of the project

Fabric Composer should be used instead of Concerto

Attached is a file that lists all the instances in the fabric-composer repository.

**Comment by mbwhite** [comment]
[mentions-of-concerto.txt](https://github.com/fabric-composer/fabric-composer/files/824088/mentions-of-concerto.txt)

**Comment by EdProsser** [comment]
By searching just in the jekylldocs folder, I've found 35 results in 12 files. Do you mind if I go through them with you tomorrow @mbwhite? Just to make sure they _all_ need to go, as some seem to be in code snippets or links.

**Comment by caroline-church** [comment]
@EdProsser @mbwhite is this now complete

**Comment by mbwhite** [comment]
I've had another scan over the code this morning. There are mentions of 'concerto' but they are not as far as I can tell in anything that comes out to the user directly - it's mostly internal variable names and also test code. Therefore I'm going to close this.

If anybody is in any piece of code and is able to change variable names etc then please do - however not worth going through as a specific job.
