### ISSUE TITLE
Adding conref and variables for documentation.

### ISSUE THREAD

**Issue by EdProsser** [fabric-composer/fabric-composer#373]
As documentation grows, having conrefs available will be more and more useful. I've done some investigating into how we can implement this in Jekyll. Seems pretty simple. 

## Context

Product/feature names are useful to be able to conref, to ease laborious task of changing them all manually should they one day be changed.

## Possible Fix

To add basic conrefs of the form {{site.data.conrefs.keyword}}:

1. Add a `_data` folder to the jekylldocs folder in fabric-composer.
2. Create `conrefs.yml` within the `_data` folder.
3. Contents in `conrefs.yml` should take the following format:
```
keyword:
    text to display
another_keyword:
    more text to display
```
4. When writing markdown docs, a conref can be created by using {{site.data.conrefs.keyword}} which in this example will display "text to display".

## Existing issues
- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

@mbwhite I'm reaching out to you via this issue to ask: Does this seem viable to you? Will it play nicely with our builds? I've tested this on my personal site, which also is a githubpages site using jekyll and it seems to work, but I use a far less sophisticated build process. So, waddya think?

If this is feasible, the followup will be defining what conrefs we need, and then just creating the `_data` folder and `conrefs.yml` file.

**Comment by EdProsser** [comment]
For more information, I've used the following for sources: 

https://jekyllrb.com/docs/datafiles/
https://releaseblueprints.ibm.com/display/CLOUDOE/Creating+content+in+markdown#Creatingcontentinmarkdown-SettingupalocalversionoftheMarkdownparserfortesting: (I don't know whether you'll have access to this)
https://github.ibm.com/Grant-Gayed/marked-it-cli/blob/master/example/conref.yml

**Comment by mbwhite** [comment]
Yes it should be perfectly feasible to do in the markdown parts of the website; we'd need to watch for the JSDoc parts, but as that is treated as input by Jekyll (just not modified) might simplify it.

JSDoc format needs some work anyway.

It's possible to install and run the Jekyll part of the part build to test out any updates... want to give it a try?

**Comment by EdProsser** [comment]
Sure. I'll pop over.

**Comment by EdProsser** [comment]
This exists in the PR today.
