### ISSUE TITLE
As a user, I can generate a skeleton business network definition

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#376]
We should extend our Yeoman generator to have an option for generating a skeleton business network definition project. This generator should do the following:

- [ ] Create a npm module project with a package.json file
- [ ] Create the business network definition directories (models and lib)
- [ ] Add sample business network definition files
- [ ] Add `npm test` support and a basic unit test to demonstrate how to do so
- [ ] Add other tools we consider best practice, such as ESLint and license-check

This will make it much easier for users to create new business network definition projects without the use of a tool such as the Composer Playground, and will help them to use best practices for developing and testing business networks.

**Comment by 14gracel** [comment]
Added #627
