### ISSUE TITLE
Playground should gracefully handle importing an invalid sample

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#381]
## Context
The grammar for ACLs has just been changed -- meaning that the sample networks temporarily contain invalid permissions.acl files.

## Expected Behavior
Should be able to import the artifacts into the Playground, even if they are invalid, or should fail with a clear message.

## Actual Behavior
Get an alert dialog with the parser exception.

## Possible Fix
We should tolerate importing samples that contain warnings or errors.

## Steps to Reproduce
1. Run the latest Playground at fabric-composer-next-unstable.mybluemix.net
2. Import the Bond sample (after authenticating with GitHub)
3. Note the error dialog "Error: Expected "rule", comment, end of line or whitespace but "I" found. Line 4 column 1"
4. Nothing was imported

## Existing issues
#382

**Comment by dselman** [comment]
We should also detect when we have invalid data in localStorage and recover.

**Comment by caroline-church** [comment]
This should just cover giving a good error message if something goes wrong

**Comment by Jakeeyturner** [comment]
Temporary fix in PR #540 until we complete Issue #541
