### ISSUE TITLE
Should not be able to submit an instance of an abstract Transaction in Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#399]
## Context
Transaction types that are abstract should not appear in the dropdown list in the Playground.

## Expected Behavior
Filter transactions and remove all abstract types

## Actual Behavior
All transaction types appear

## Steps to Reproduce
1. Import the AnimalMovement sample
2. Submit a transaction
3. Note that the abstract AnimalMovement transaction type is displayed in the dropdown

**Comment by nklincoln** [comment]
fixed with #408
