### ISSUE TITLE
Submit Transaction in Playground should not require timestamp and id

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#404]
## Context
Factory.newTransaction will automatically assign the timestamp and identifier for a transaction, so we should not be asking for these properies in the UI.

## Expected Behavior
Allow the user to submit a transaction without manually specifying the transaction id and timestamp.

## Actual Behavior
Have to supply the properties by hand.

## Steps to Reproduce
1. Try to submit a transaction
2. Note that timestamp and id are required.

## Existing issues

- [x] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [x] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [x] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
Slows me down. Makes me enter ISO 8601 date/times by hand. Makes it more likely to get duplicate transaction ids.

## Your Environment

* Version used: Latest Playground
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Safari Mac OS X
* Link to your project:

**Comment by nklincoln** [comment]
Proposed changes are to use a map that holds hidden parameters (timestamp/id) that are used when required to strip out, or add to, the resource definition. We are using the serialiser to create a resource from the json description, which requires a resource identifier to be present - this can be provided as a generated uuid from the hidden parameters.

I also propose that preparation for the task in #409 is made, which will be making a change to the resource generator to accept new options, indicating a specific set of "empty" properties upon generation. This would result in a resource definition always being generated with values until the modification in 409 is made, at which point only a minor parameter edit would be required within the transaction component code.

**Comment by nklincoln** [comment]
fixed under #446
