### ISSUE TITLE
Import/Replace divs at the bottom of Left Hand Nav panel

### ISSUE THREAD

**Issue by samjsmith** [fabric-composer/fabric-composer#405]
## Expected Behavior

The Import/Replace and Export should flow nicely below the Files section

## Actual Behavior
It goes right to the bottom of the page.

## Possible Fix
CSS styling issue

## Steps to Reproduce
1. Go to playground UI
2. Observe bug
3. Drink tea
4.

## Existing issues

- [ x ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ x ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ x ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

I was trying to find the Import/Replace option

## Your Environment

* Version used: 0.4.5
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by bestbeforetoday** [comment]
Should be resolved by #442, so closing.
