### ISSUE TITLE
Export BNA from Playground on Safari does not name the file

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#407]
## Context
When a BNA is exported from Playground using Safari the file is pushed to downloads but is named "Unknown" without a file extension.

## Expected Behavior
The file is pushed to downloads and has a name (Firefox behavior).

## Actual Behavior
The name of the file is "Unknown" when downloaded.

## Steps to Reproduce
1. Press the Export business network button
2. Open the Downloads folder, see that the file downloaded is called Unknown.

## Existing issues

- [x] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [x] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [x] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used: Latest Playground
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari 10.0.3
* Operating System and version (desktop or mobile): Mac OS X 10.12.3
* Link to your project:

**Comment by Jakeeyturner** [comment]
This is a known issue https://github.com/eligrey/FileSaver.js/issues/194

**Comment by caroline-church** [comment]
maybe we need to use a different library for this?

**Comment by Jakeeyturner** [comment]
It seems to be an issue with Safari as it doesn't support the HTML5 download attribute. I can investigate a workaround but won't be able to test it out.

**Comment by fenglianxu** [comment]
I have come across this issue in Safari browser as well.  The exported filename is called **Unknown**, it would be nice to have default file name as the existing network filename.

**Comment by 14gracel** [comment]
The latest update to Safari (released 27th March) seems to support the tag http://caniuse.com/#feat=download

**Comment by sstone1** [comment]
Can confirm that this functionality does work as expected on Safari 10.1.
It looks like Safari 10.1 is available for Mac OS 10.10, 10.11, and 10.12.
Given how happy (usually!) Mac users are to upgrade, and the work required to resolve this problem another way, I vote that we just close this.
