### ISSUE TITLE
Generate valid empty/stub JSON for assets on asset registry page

### ISSUE THREAD

**Issue by bestbeforetoday** [fabric-composer/fabric-composer#409]
Currently all properties are assumed to be string type and are given a default empty string value (""). This immediately fails JSON validation where properties are defined a non-string types.

The stub JSON is generated in generateDefinitionStub() of packages/composer-playground/src/app/resource/resource.component.ts.

**Comment by dselman** [comment]
This is probably best fixed by adding an option to the existing sample data generator to generate "empty" data for all required properties -- i.e. all strings would be "", numbers would be 0, array would be empty. We could even add an option to the UI to also generate optional properties.
