### ISSUE TITLE
UI Header and Main page divider lose alignment at larger window widths

### ISSUE THREAD

**Issue by samjsmith** [fabric-composer/fabric-composer#415]
## Context

I'll upload an image to illustrate:
![image](https://cloud.githubusercontent.com/assets/16335033/23760707/758fa318-04e8-11e7-950e-96e9a2ee1de7.png)

## Expected Behavior

I expect the dividers to remain aligned 

## Actual Behavior

They are sometimes aligned

## Possible Fix

CSS Styling

## Steps to Reproduce

1. Go to UI
2. make browser window wide
3. observe problem

## Existing issues

- [ x ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ x ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ x ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): 	56.0.2924.87 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): OSX Sierra
* Link to your project:

**Comment by samjsmith** [comment]
This may well be expected behaviour and I know it's a small problem but I thought I'd raise it :)

**Comment by winslet** [comment]
I fixed this yesterday? should have gone in...

**Comment by winslet** [comment]
@caroline-church think this is the same as Nitpick 12 👍

**Comment by caroline-church** [comment]
yeah its the same and i've fixed it so closing
