### ISSUE TITLE
Submit transaction button in wrong place in playground

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#416]
## Context

The submit transaction button is on the left hand pane. On Safari it is stuck to the left hand side of the window (looks like bug), but on Firefox it appears to be properly centered in the left hand pane.

Additionally, the message does not match up with the UI when there are no transactions in the registry:
`To create resources in this registry click create new at the top of this page`

## Expected Behavior

I was confused not to find the submit transaction button in the same place as the create asset/participant button when I was on the transaction registry. I'm assuming that it was designed this way, so I can easily submit transactions from the asset/participant registries? I might just be refusing to move on from the location of the button in the old UI 😉 

## Actual Behavior

The submit transaction button is on the left hand pane.

## Possible Fix

Fix the Safari display bug, fix the empty registry text.

## Steps to Reproduce

1. Go to playground
2. Click on test tab
3. See transaction button in left hand pane

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

It works, but looks pretty rubbish in demos!

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by nklincoln** [comment]
Dealt with in #457
