### ISSUE TITLE
Updating a business network in Playground jumps to another file

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#417]
## Context

If I make a change to a file, and then click Update, then the update succeeds... but the editor jumps to another, seemingly random file.

## Expected Behavior

I think the editor should stay on the currently selected file.

## Actual Behavior

The editor jumps to another, seemingly random file.

## Possible Fix

Stop the editor jumping to another file after clicking the Update button.

## Steps to Reproduce

1. Make change to business network
2. Click Update button
3. See editor change files

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

Trying to keep editing and testing changes on one file

## Your Environment

* Version used: unstable-next
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

**Comment by samjsmith** [comment]
@sstone1 I've thought the same thing when you switch from the Define to Test panel and back again.  I think getting the update button to not switch is pretty straightforward and restricted to a fix in the editor component.
Switching back and forth between Define and Test (which is a reasonable user task - I define something, go to the test panel and create one, go back to redefine it...) is a bigger thing and perhaps needs a new service to allow the editor to 'remember' where it was last.
I'll have a look at addressing both here.
