### ISSUE TITLE
Playground header gets stuck as "Editing package.json"

### ISSUE THREAD

**Issue by EdMoffatt** [fabric-composer/fabric-composer#421]
## Context
In the Playground, after clicking "View/edit full metadata in package.json", the header in the main body of the page stays at "Editing package.json" even after you navigate away.  This means it's no longer to see or edit the Business Network Definition name and version in the UI.
The padding on the title is also off?  Whatever the cause, the symptom is that the editor renders too high up, slightly overlapping the text of the header.

## Expected Behavior
After clicking to edit package.json, behaviour is correct, but padding should be fixed so that the code editor does not overlap the title (as shown here):
![image](https://cloud.githubusercontent.com/assets/7454304/23792281/2e8ad578-057e-11e7-8ee9-97ed9791d530.png)

Then, when the user clicks anything in the left hand nav, they should go back to that page, with the appropriate header.  e.g. when they click "Script File, this should be what they see:
![image](https://cloud.githubusercontent.com/assets/7454304/23792318/568ae8ec-057e-11e7-95c4-1e39d9e01ff1.png)

## Actual Behavior
Header padding is out as shown in previous section (1st screenshot).
And if the user navigates awa the title doesn't change back, as shown here:
![image](https://cloud.githubusercontent.com/assets/7454304/23792341/734438da-057e-11e7-9d02-893efa4d7a09.png)

## Steps to Reproduce
1. Click the edit pencil icon next to the Business Network name
2. Click the "View/edit full metadata in package.json" link on the right
3. Click a left-hand-nav link e.g. "Script File"

## Your Environment
* Version used: v0.5.0
* Environment name and version: Chrome 56.0.2924.87 (64-bit) (incognito) pointed at fabric-somposer-next-unstable.mybluemix.net
* Operating System and version: MacOS

**Comment by caroline-church** [comment]
Fixed
