### ISSUE TITLE
Modify docs build to push unstable and release docs

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#422]
## Context

@EdProsser is going to be making large-scale changes to our documentation.
We need to give him a staging area so he can deliver changes on a regular basis without it affecting the main released documentation (which might cause our users confusion).
This is a good idea anyway as it means we will be able to merge in docs changes with the associated code changes, but not have both docs + code seen by end users until we cut a release.

@14gracel thanks for volunteering, give @mbwhite a shout if you want some pointers.

Marking as P1 as we want this work done ASAP.

**Comment by mbwhite** [comment]
The `.travis/deploy_docs.sh` is the script file that runs in a merge build to push up the docs to the docs repo. 

Suggested solution is add in the `${TRAVIS_BUILD_NUMBER}` variable to the path of the directory that is created. But only for the builds that are not `TAG` builds.. i.e. not release.
