### ISSUE TITLE
Clicking on View App button after successfully deploying Car Lease demo app to Bluemix results in "Identity or token does not match" error

### ISSUE THREAD

**Issue by sanjay-saxena** [fabric-composer/fabric-composer#425]
Used this [tutorial](https://console.ng.bluemix.net/docs/services/blockchain/ibmblockchain_tutorials.html) to deploy `Car Lease` demo app to Bluemix while working on the first part of the three-part Blockchain developer course. The deployment went clean and the app was operational. I let the app and the service run overnight so that I could continue with the second part of the three-part course the next day. 

However,  when I tried to interact with the app the next day, I received an error message in the red banner at the top of the page saying that I should delete both the app and the service and try again. So, I deleted both the app and the service using the Bluemix dashboard and deleted the project from hub.jazz.net. Then, I followed the process to deploy the `Car Lease` demo once again. The deployment goes clean again and I see a green circle indicating that the app is running. But, when I tried to view the app, I see the familiar red banner with the error message saying that I should delete both the app and the service and try again. Also, the error message includes `Identity or token does not match`.

Digging a bit deeper into the logs, I see errors and a potential stack trace as shown below:

```
APP/0 designed for a production environment, as it will leakMar 10, 2017 11:30:31 AM
APP/0 [!] VCAP_SERVICES detectedMar 10, 2017 11:30:32 AM
APP/0 peer0: grpcs://0142b35d5dc94f76a00c7957f78493cc-vp0.us.blockchain.ibm.com:30004Mar 10, 2017 11:30:32 AM
APP/0 peer2: grpcs://0142b35d5dc94f76a00c7957f78493cc-vp1.us.blockchain.ibm.com:30004Mar 10, 2017 11:30:32 AM
APP/0 peer3: grpcs://0142b35d5dc94f76a00c7957f78493cc-vp3.us.blockchain.ibm.com:30004Mar 10, 2017 11:30:32 AM
APP/0 Server UpMar 10, 2017 11:30:32 AM
APP/0 ERROR	Startup	OUTPUT: "Failed to enroll registrar with WebAppAdmin abde14b29c"Mar 10, 2017 11:30:33 AM
APP/0 at /home/vcap/app/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }Mar 10, 2017 11:30:33 AM
APP/0 at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)Mar 10, 2017 11:37:01 AM
APP/0 at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:317:13)Mar 10, 2017 11:37:01 AM
APP/0 at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)Mar 10, 2017 11:37:01 AM
APP/0 at /home/vcap/app/app.js:279:5Mar 10, 2017 11:37:01 AM
APP/0 at /home/vcap/app/node_modules/express/lib/router/index.js:284:7Mar 10, 2017 11:37:01 AM
APP/0 at /home/vcap/app/app.js:286:15
APP/0 { Error: Identity or token does not match.Mar 10, 2017 11:30:33 AM
APP/0 ERROR	Startup	OUTPUT: {"code":2,"metadata":{"_internal_repr":{}}}
```

## Context
See above.

## Expected Behavior
The app should deploy and function correctly.

## Actual Behavior
See above description.

## Steps to Reproduce
1. Deploy `Car Lease` demo app to Bluemix. Let it run overnight.
2. Try to interact with it next day.
3. Delete the app and the service. And, the project from hub.jazz.net.
4. Try redeploy `Car Lease` demo app to Bluemix and click on the View App button.

## Context
Trying to complete the three-part developer course for Blockchain.

## Your Environment
* Version used: The one available on Bluemix.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Bluemix
* Operating System and version (desktop or mobile): Bluemix
* Link to your project: https://hub.jazz.net/project/sscarleaseblockchain/car-lease-demo-sscarleaseblockchain-1125

**Comment by sstone1** [comment]
@sanjay-saxena this problem is nothing to do with fabric-composer; I suggest you raise it at the IBM owned car-lease-demo repository: https://github.com/IBM-Blockchain/car-lease-demo
