### ISSUE TITLE
Composer fails to work reliably with IBM HSBN service

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#427]
## Context

Composer fails to work reliably with the IBM HSBN service. The following SSL connection error is frequently seen, although sometimes the connection is OK:

```
E0311 17:00:18.374950950   18878 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0311 17:00:18.375110153   18878 handshake.c:128]            Security handshake failed: {"created":"@1489251618.375088357","description":"Handshake failed","file":"../src/core/lib/security/transport/handshake.c","file_line":264,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
events.js:160
      throw er; // Unhandled 'error' event
```

I suspect this error would occur against any instance of Hyperledger Fabric that has been configured with SSL certificates, but we are currently unable to test that - when we are finished setting up v1.0 system tests we should get those running against an SSL secured instance (FYI @davidkel).

## Expected Behavior

No errors should occur.

## Actual Behavior

Errors occur.

## Possible Fix

The problem seems to be caused by us trimming the final newline off of the PEM certificates that we pass to the `hfc` module. No idea why this causes the problem, or why it sometimes works, but easy enough to fix.

## Steps to Reproduce

1. Try to deploy Composer to IBM HSBN service
2. Run composer commands in a loop trying to recreate problem

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

Made me sad 😢 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by davidoevans** [comment]
I seem to have recreated this issue on the latest IBM Blockchain Platform (IBP) Enterprise.  I had a queue of 5 threads adding Composer assets to our IBP Fabric using identity 'sleeper'.  Each request was creating a new BusinessNetworkConnection.  Everything was going fine until I received the these error messages.

`E1002 17:22:16.908102000 140736833737664 ssl_transport_security.c:602] Could not add root certificate to ssl context.
E1002 17:22:16.908180000 140736833737664 ssl_transport_security.c:1348] Cannot load server root certificates.
E1002 17:22:16.908217000 140736833737664 security_connector.c:837]     Handshaker factory creation failed with TSI_INTERNAL_ERROR.
E1002 17:22:16.908225000 140736833737664 secure_channel_create.c:127]  Failed to create secure subchannel for secure name 'dal-zbc01b.5.secure.blockchain.ibm.com:20384'
E1002 17:22:16.908229000 140736833737664 secure_channel_create.c:158]  Failed to create subchannel arguments during subchannel creation.
E1002 17:22:18.070898000 140736833737664 ssl_transport_security.c:455] Corruption detected.
E1002 17:22:18.070963000 140736833737664 ssl_transport_security.c:427] error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table
E1002 17:22:18.070974000 140736833737664 secure_endpoint.c:185]        Decryption error: TSI_DATA_CORRUPTED`

Any subsequent attempts to connect using the sleeper user id now return error:

`"Error: Error trying to ping. Error: Error trying to query chaincode. Error: chaincode error (status: 500, message: Error: The current identity has not been registered:sleeper)"`

I was able to list the identity, revoke the identity.

`$ composer identity revoke -p healthchain-testnet -n healthchain-network -i acole -s SFrNwoDJmnEK -u f863937cf4f809ec2a40b4004b2ff6d4b2b7f56a693ee2f6e3cad08bd4c723fc

The identity 'f863937cf4f809ec2a40b4004b2ff6d4b2b7f56a693ee2f6e3cad08bd4c723fc' was revoked and can no longer be used to connect to the business network.

Command succeeded`

I was not able to reissue the identity.

`$ composer identity issue -p healthchain-testnet -n healthchain-network -i acole -s SFrNwoDJmnEK -u sleeper -a "resource:org.healthchain.AccountAdmin#jeff@healthchainrx.com" -x false

Error: fabric-ca request register failed with errors [[{"code":0,"message":"Identity 'sleeper' is already registered"}]]

Command failed`

I adding another participant, issued them an identity but subsequent attempts to use the environment in any way failed.
