### ISSUE TITLE
Relationships to types in other namespaces get corrupted

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#469]
## Context

Raised by @pastadin; he is seeing relationships that have an identifier where the fully qualified type is repeated. For example:

`medicalRecords.participants.Patient#medicalRecords.participants.Patient#medicalRecords.participants.Patient#PATIENT:001`

## Expected Behavior

The identifier of a relationship should always be the identifier of the actual resource. The type information should never be part of the identifier.

## Actual Behavior

The type information is being parsed into the identifier of the relationship.

## Possible Fix

The code currently checks to see if the resource containing the relationship field is in the same space as the resource being referenced by the relationship. If they are the same namespace, just the identifier is serialised. If they are in different namespaces, then the fully qualified identifier is serialised.

However, there is no relationship parsing code for the fully qualified identifier, so the fully qualified identifier is used as the identifier when parsed. We should just bin this check as it doesn't work, and is not required when referring to types in other namespaces.

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dselman** [comment]
The rationale for including the type information is that it allows someone to resolve the relationship without having to introspect the model. We should rethink this use case however, as I suspect with custom registries & links we're going to need to make changes.

**Comment by sstone1** [comment]
@dselman agreed, think there's a lot of work to do in this area.

**Comment by dselman** [comment]
Increased priority as this has now been reported on RocketChat.

**Comment by sstone1** [comment]
This is fixed, have confirmed that the fix is available in v0.5.5.
