### ISSUE TITLE
Check for python in pre-req script for Ubuntu 16.04

### ISSUE THREAD

**Issue by silliman** [fabric-composer/fabric-composer#478]
## Context

I'm not saying this is a bug, but just an enhancement request to make an end user's life a little easier.
Python is a pre-req for composer, since node-gyp requires it.  In the ubuntu/xenial64  vagrant box provided by Hashicorp (20170311.0.0. version at least) python doesn't seem to be installed.   So after running through the prereqs-ubuntu16.sh script that you provide, the global npm install of composer-cli fails since node-gyp can't find python.

I fixed this by just doing an apt-get install of python-minimal.   ubuntu suggested I try installing python-minimal or python3 so I just randomly selected python-minimal to try first.

## Expected Behavior

Ideally the prereqs script would check for the presence of python and install it if it is not present.

## Steps to Reproduce

1.  In a cygwin terminal session, from a fresh directory on my laptop,   `vagrant init ubuntu/xenial64`
2.  `vagrant up`
3. ` vagrant ssh`
4.  from my xenial64 session,  I grabbed your pre-reqs script with  `curl -O https://raw.githubusercontent.com/mbwhite/sample-applications/master/packages/getting-started/scripts/prereqs-ubuntu16.sh`
5. `chmod u+x prereqs-ubuntu16.sh`
6. `./prereqs-ubuntu16.sh`
7. I logout and login again, as instructed at successful end of prereqs-ubuntu16.sh
8. `npm install -g composer-cli`      goes belly up due to python not being installed

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mbwhite** [comment]
See https://github.com/fabric-composer/sample-applications/pull/13

**Comment by davidkel** [comment]
hadn't realised this was unassigned from me so I fixed it :-)
