### ISSUE TITLE
As a fabric-composer admin/user I need to stand up Playground-UI in my own cloud

### ISSUE THREAD

**Issue by mbwhite** [fabric-composer/fabric-composer#485]
## Context
Currently, there are instructions for how to access the Playground-UI in Bluemix and stand it up in docker containers on my own local machines. But I have others already in <another cloud> can you show it working somewhere else and how it was done please?

## Expected Behavior
Be able to access a running instance of the Playground - not stood up in Bluemix

## Actual Behavior
Nothing as yetl

**Comment by mbwhite** [comment]
# Setting up on Digital Ocean

Goal: to have the composer-ui running on a Digital Ocean 'droplet' 

 - Create a new Droplet - using the Docker 17 on 16.04 Ubuntu 'one-click' app
 - For running a full Hyperledger Fabric - this will need to have 1gb + memory
 - Log into the console with details as provided by DigitalOcean
 - Current instructions are at https://fabric-composer.github.io/start/getting-started-playground.html

 - Docker is preinstalled but docker-compose is not. Follow the curl to get the docker-compose and modify the script's permissions
 - Follow the instructions to get the docker images and startup the docker-compose script.

The playground will now be running on DigitalOcean droplet!  port 8080

**Comment by Hefziben** [comment]
hello Matthew, could you please provide me an updated tutorial for this?
