### ISSUE TITLE
Loopback Connector is being published with the wrong project name

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#54]
The Loopback Connector is checked in as `composer-loopback-connector` but the Loopback Framework requires that we publish it as `loopback-connector-composer`. Both the package name and folder need changing.

**Comment by samjsmith** [comment]
Done in #59.
@Jakeeyturner can you remove the old `composer-loopback-connector` package from the npm repo once the new `loopback-connector-composer` package has been pushed up there please?

**Comment by Jakeeyturner** [comment]
Due to [npm's policy,](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) I've had to send a support ticket to npm in order to delete the old 'composer-loopback-connector'.

Will keep this issue informed.

**Comment by Jakeeyturner** [comment]
Npm now states that 'composer-loopback-connector' is deprecated.
