### ISSUE TITLE
As a user I would like the ability to apply a single rule to more than one resource, participant, or operation at a time

### ISSUE THREAD

**Issue by jdockter** [fabric-composer/fabric-composer#555]
As a fabric developer I would like the ability to apply a single rule to more than one resource, participant, or operation.  For example, I want three different participants to be able to create an order or I want one participant to have update and delete authority for an asset.  Something like the following:

rule POCreate {
      description: "A PO Provider can create a Purchase Order"
      participant: procurement.contingentLabor.POProvider, ibm.procurement.contingentLabor.BuyerPM"
      operation: CREATE
      resource: "procurement.contingentLabor.PurchaseOrder"
      action: ALLOW
 }

## Context
Today I don't see an example (https://fabric-composer.github.io/reference/acl_language.html) of how to have more than one resource or participant applied to a single rule.  I've tried different syntax to make this work but doesn't seem to be supported.

## Expected Behavior
See context above

## Actual Behavior
When trying to provide multiple values in one rule I get a syntax error in composer web

## Possible Fix
NA

## Steps to Reproduce
NA

## Existing issues

- [ ] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [X] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)
https://chat.hyperledger.org/channel/fabric-composer?msg=xYdh9CbhPRmx7yHSm

## Context
With many participants and resources in a business network I don't want to have to maintain 10s or 100s of rules, but would rather group them together when possible.

## Your Environment
* Version used: 0.5.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dselman** [comment]
You should be able to use types, or type inheritance to limit the number of rules.

**Comment by jdockter** [comment]
Any chance you could provide an example of this?  I see we can use &&, might also be good to have an example of that here, https://fabric-composer.github.io/reference/acl_language.html

**Comment by dselman** [comment]
Couple of thoughts here:
- If Person is a base class, and you have Manager and Employee that extend Person, then you should be able to write ACL rules about instances of Person and have them applied to instances of Manager or Employee
- If your participant has a field called `type` or `role` then you could write ACL rules about the value of this field.

**Comment by dselman** [comment]
I am going to close this as we have workarounds and are unlikely to get to this issue anytime soon.
