### ISSUE TITLE
Request for composer connection profile to be based on Environmental Variables

### ISSUE THREAD

**Issue by paul-at-ibm** [fabric-composer/fabric-composer#602]
This is not a request for bug fix but a request for new feature.

Currently Fabric composer relies on file based connection profile to link with Fabric backing services. This is a request for the connection profile to be served as environmental variables to make it OS agnostic and 12-factor app compliance.

## Context

We proposed that composer follow Cloud Foundry styled VCAP services profile. An example is illustrated below:

```
VCAP_SERVICES={
        "ibm-blockchain-5-prod":[
            //--bluemix v0.6 config--//
        ],
        "fabric-composer":[
            {
                "connections": {
                    "type":"hlf",
                    "membershipServicesURL":"grpc://localhost:7054",
                    "peerURL":"grpc://localhost:7051",
                    "eventHubURL":"grpc://localhost:7053",
                    "keyValStore":"<path to keystoreval>",
                    "deployWaitTime":"300",
                    "invokeWaitTime":"100",
                    "networks":{
                        "marbles":"<UUID>"
                    }
                }
            },

        ]

    }
```
This will ensure that:

a) Web apps developed against Fabric Composer business network can be deployed as cloud foundry runtimes but not exclusively e.g:

const BusinessNetworkConnection = require('composer-client').BusinessNetworkConnection;

BusinessNetworkConnection currently requires file based profile but a concept that does not exist in cloud foundry runtime environment.

b) Ensure that composer-cli is not dependent on file to support deployment in a CI/CD build pipeline.

## Expected Behavior

Any parts of Fabric composer that needs connectivity to fabric network should only draw configuration from environmental variable, e.g.:

export VCAP_SERVICES={}
export DESIGNATED_PEERS=<Name of peer or peer id> // incase VCAP_SERVICES returns configurations of more than one peer.

## Actual Behavior

This would allow for Fabric composer based app and/or deployment to be able to change configurations over its entire life cycle from development to production without the need to rely on platform specific files.

## Possible Fix

Please refer to https://github.com/blockchainlondon/fabric-in-the-cloud for suggestions.

**Comment by dselman** [comment]
Connection profiles are also loaded from the COMPOSER_CONFIG environment variable. This should be a JSON string with a root `connectionProfiles` key, with a set of connection profiles indexed by name.
