### ISSUE TITLE
$class on the API breaks Java client generation

### ISSUE THREAD

**Issue by gcharters** [fabric-composer/fabric-composer#610]
The APIs generated by Composer includes an attribute called $class.  This causes problems when generating Java Clients from the Swagger because the model classes contain a _String getClass()_ method that conflict with _Class Object.getClass()_.  For example,

@ApiModelProperty(value = "The class identifier for this type")
@JsonProperty("$class")
public String getClass() {
return _class;
}

## Context
This is an issue of anyone trying to call a Composer API from Java.

## Expected Behavior
I expect to be able to generate a Java Client from the Composer Swagger than compiles.

## Actual Behavior
The generted Java client code does not compile.

## Possible Fix
I think there are two possibilities:
1. Rename $class to something else, such as $type.
1. Remove the need for this attribute altogether.  Given the information is static, it seems like it should be inferred from the endpoint and not required in the API.  

## Steps to Reproduce
I produced this using the WebSphere Developer Tools on Eclipse, which are based on the Swagger Java tools.  I'd be happy to test any fix.  The steps in WDT are:
1.  Import the json into a Dynamic Web Project
1.  Right click on the project and choose REST-ful services -> Generate JAX-RS Client....

## Existing issues
https://github.com/fabric-composer/fabric-composer/issues/329

## Context
Trying to right a demo calling Fabric Composer from Java.  Means I have to significantly modify the code and bundle my own Jackson implementation to get it to work.

## Your Environment
Eclipse Neon Release (4.6.0)
WebSphere® Application Server Developer Tools for Eclipse
Version: 16.0.0.3
Build id: 20160908_1547

**Comment by dselman** [comment]
I think the $class is required to specify the concrete types returned/passed. For example, the model may specify that an asset has a collection of abstract types, and at runtime a collection of types derived from the abstract types could be validly returned.

Swagger 2.0 supports polymorphism:
http://stackoverflow.com/questions/27862407/swagger-inheritance-and-composition

Now I don't know if we are generating our Swagger correctly to indicate that $class is the discriminator property. @sstone1 -- do you know?

I also think this sounds like a bug in the Java tools -- they should be mangling the properties so they do not conflict with system types.

**Comment by sstone1** [comment]
We don't attempt to give LoopBack the full type hierarchy; each LoopBack model includes all of the properties for that type, including the inherited ones. Bear in mind that we do not generate the Swagger; LoopBack generates the Swagger for us from the LoopBack model.

JSON supports any valid JSON string value as a key in a JSON object, including "$class" and "class". It seems that the latest levels of the official Swagger Codegen tools do the right thing:

```
@SerializedName("$class")
private String propertyClass = "org.acme.vehicle.auction.Auctioneer";

@ApiModelProperty(example = "null", value = "The class identifier for this type")
public String getPropertyClass() {
  return propertyClass;
}

public void setPropertyClass(String propertyClass) {
  this.propertyClass = propertyClass;
}
```

This is a bug in the Java code generator you are using @gcharters, you should raise the problem with the people responsible for those tools. Closing.

**Comment by gcharters** [comment]
Thanks, @dselman and @sstone1 - I'll mention it to our tools folks.  It might be we just need to pick up a more recent level.
