### ISSUE TITLE
Error in QuickStart Guide (No registered namespace)

### ISSUE THREAD

**Issue by opiepj** [fabric-composer/fabric-composer#642]
## Context

Following the quick start [guide](https://fabric-composer.github.io/installing/quickstart.html)

in `packages/getting-started` I get the error during install.

During the install process (deployNetwork) I get:

```bash
Looking for package.json of Business Network Definition in /Users/patrick.opie/Documents/github/blockchain/fabric-composer-example/sample-applications/packages/getting-started/node_modules/digitalproperty-network
composer archive create --archiveFile digitialPropertyNetwork.zip --sourceType module --sourceName digitalproperty-network

Options:
  --help             Show help  [boolean]
  -v, --version      Show version number  [boolean]
  --archiveFile, -a  Business network archive file name. Default is based on the Identifier of the BusinessNetwork  [string]
  --sourceType, -t   The type of the input containg the files used to create the archive [ module | dir ]  [required]
  --sourceName, -n   The Location to create the archive from e.g. NPM module directory or Name of the npm module to use  [required]

No registered namespace for type net.biz.digitalPropertyNetwork.RegisterPropertyForSale
```
Failing the installation.
## Expected Behavior

Installation should work.

## Actual Behavior

Installation isn't working, I cannot follow the tutorials...

## Steps to Reproduce

1. git clone https://github.com/fabric-composer/sample-applications.git
2. cd sample-applications/packages/getting-started
3. npm install
4. Breaks

## Existing issues

- [x] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [x] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [x] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context

I don't have much context on what the issue is.

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): OSX 10.11
* Link to your project: https://github.com/1337programming/fabric-composer-example
* Docker: Docker version 17.03.0-ce, build 60ccb22
* Docker-Compose: docker-compose version 1.11.2, build dfed245
* Node.JS: 6.7
* npm: 3.10

**Comment by opiepj** [comment]
Linked to [issue](https://github.com/fabric-composer/sample-networks/issues/27)

**Comment by jthub** [comment]
This should have been fixed in the latest release https://github.com/fabric-composer/fabric-composer/releases/tag/v0.5.10

**Comment by opiepj** [comment]
yeap was on 5.9, all good now.
