### ISSUE TITLE
Installation issue : hashtable@2.0.2

### ISSUE THREAD

**Issue by PPCM** [fabric-composer/fabric-composer#687]
Initial installation issue for fabric-composer

## Context
npm ERR! Linux 4.9.0-2-amd64
npm ERR! argv "/root/.nvm/versions/node/v6.10.2/bin/node" "/root/.nvm/versions/node/v6.10.2/bin/npm" "install" "-g" "composer-cli"
npm ERR! node v6.10.2
npm ERR! npm  v4.3.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the hashtable@2.0.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

## Steps to Reproduce
1. npm install -g composer-cli

## Your Environment
Docker Engine: Version 17.03.1-ce, build c6d412e
Docker-Compose: Version 1.12.0, build b31ff33
Node: 6.10.2
npm: 4.3.0
git: 2.11.0

**Comment by dselman** [comment]
Appears to be fixed by installing Python:
https://github.com/chad3814/node-hashtable/issues/28

**Comment by PPCM** [comment]
Python is already installed: Python 2.7.13

**Comment by dselman** [comment]
Do you have the same issues when using Node 6.9.5?

**Comment by Jamiek94** [comment]
I only had this problem when I was logged in as root.

I was able to install the composer-cli by executing the following command first:

`
npm config set unsafe-perm true
`

**Comment by johnm** [comment]
On Mac OS 10.12.4, I had to downgrade to node v6.10 and run npm config set unsafe-perm true  to get this to complete.

**Comment by isasameasb** [comment]
Even i am having the same issue.Can anyone post a solution?

**Comment by prakashn** [comment]
i am having the same issue. 
Running 
Ubuntu 16.04.2 LTS
docker 17.03.1-ce
docker-compose version 1.13.0, build 1719ceb
node v 6,9,5
npm v 3.10.10 

Is there a solution?

**Comment by mbwhite** [comment]
Please make sure that you have nom v4.6 as well. 
I understand that this hashtbale is being removed as fabric-client dependency in the very near future.

**Comment by prakashn** [comment]
nom 4.6?  or npm 4.6? Can you please clarify

**Comment by prakashn** [comment]
Tried with npm 4.6 too. No change. Assume this will get fixed when the dependency is removed.

**Comment by sativ01** [comment]
Folks, for Ubuntu 16.04 64bit
I've had the same issue
I have installed nodejs with:
sudo apt-get install nodejs

but for some reason the correct way to install is:
sudo apt install nodejs-legacy

after that the error was gone

**Comment by alisonbibm** [comment]
Marvellous, thank you for the tip!

**Comment by mr-j-sinclair** [comment]
@johnm  How did you downgrade to node 6.10?

**Comment by jjill86** [comment]
My previous comment is actually fixing one problem but causing another.
`sudo apt install nodejs-legacy`
installs node 4.x which will not work correctly later

so the correct way to install node js - from nodejs.org:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by mbwhite** [comment]
FYI I've tried Ubuntu 16 with the node 6.10 and didn't see any issues.
Could you confirm what version of python is being used please.

**Comment by luncliff** [comment]
I was suffering with the same issue. But solved it a minute ago.
After updating NPM to `5.3.0`, the setup script worked well. (`npm install -g npm`)

### Environment
 - Windows 10 Pro, 64-bit
 - Node.js: `6.11.1`
 - NPM: from `3.10.10` to `5.3.0`
 - Python: `2.7.13`

**Comment by zachgoll** [comment]
I just installed it from the github repo and worked fine.

cd ~
npm install "https://github.com/fabrice102/node-hashtable.git"
npm install
