### ISSUE TITLE
Prerequisites page contains Whitewater related content

### ISSUE THREAD

**Issue by winslet** [fabric-composer/fabric-composer#70]
Hi all, 

Seems like we may have some leftover content on the prerequisites page: https://fabric-composer.github.io/tasks/prerequisites.html

![image](https://cloud.githubusercontent.com/assets/13980028/22599602/6734067a-ea2f-11e6-83bc-44bbcee39624.png)

Now we're fully open can we remove this information?

Thanks! (also apologies if im not doing anything correctly - this is my first issue!)

**Comment by nklincoln** [comment]
Fixed with #188
