### ISSUE TITLE
As a user I should be able to tell which version of Composer Playground I am using

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#86]
We need some sort of About Box that reports the versions of npm modules being used.

**Comment by EdMoffatt** [comment]
Plan is for this to live on the "Connection Profiles" tab.  See page 24 in the latest low-fi designs: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

(Sam to provide hi-fis shortly!)

**Comment by winslet** [comment]
Hifi provided here (see bottom left hand corner "about" section)

![Fabric_Composer_Playground_Connection_Profiles](http://static.gitscout.com/d4d5d87977bd963d6e9ee1a823d2d15ce8f9b67ce1eeb10f17b42fc1b512141e.png)

Styles for @14gracel to use:

header text is a "h2" tag with $primary-text colour
paragraph text is a "p" tag with $secondary-text colour in SCSS

(eg ![gitscout-image-from-clipboard-1](http://static.gitscout.com/69fae484bf1b7438bd808c87009b5b8a646299c0010e1d45ec5b4ad8ef9ef09d.png)

**Comment by 14gracel** [comment]
#247
