### ISSUE TITLE
Numeric range validation not being enforced

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#87]
Modify the Vehicle Auction sample model to add numeric range validation:

`transaction Offer identified by transactionId {
  o String transactionId
  o Double bidPrice range=[0,]
  --> VehicleListing listing
  --> User user
}`

Then submit an Offer transaction:

`{
  "$class": "org.acme.vehicle.auction.Offer",
  "bidPrice": -100,
  "listing": "LISTING_001",
  "user": "daniel.selman@uk.ibm.com"
 }`

Note that the transaction is processed, despite having a negative bid price.

**Comment by samjsmith** [comment]
This is a problem with the file https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-common/lib/introspect/numbervalidator.js

The ast that's being passed in is not the same as that which has been used in the unit tests and so the wrong values are being tested in the various ifs/elses.

I've re-done the tests to use updated AST values and then applied fixes to the failing testcases so this should work as designed now.
