### ISSUE TITLE
Several links are broken in the docs

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#92]
Worth finding a link checker to find all broken links

**Comment by dselman** [comment]
https://validator.w3.org/checklink/docs/checklink?uri=https%3A%2F%2Ffabric-composer.github.io&summary=on&hide_type=all&recursive=on&depth=3&check=Check

**Comment by nklincoln** [comment]
https://fabric-composer.github.io/jsdoc/module-composer-client.TransactionRegistry.html

is the only broken link discovered  (linking to https://fabric-composer.github.io/jsdoc/Registry.html)

**Comment by EdProsser** [comment]
I feel like I can grab this one. Seems to be a pretty limited set of links which are broken using the checking tool above. Might need to ask a couple of questions about where they _should_ be linking to.

**Comment by EdProsser** [comment]
These are changed in my PR coming in today. Will close when it's in.
