### ISSUE TITLE
As a user I will be able to find a list of instructions detailing how I set up my local machine to develop a business network definition

### ISSUE THREAD

**Issue by 14gracel** [fabric-composer/fabric-composer#96]
We currently have https://fabric-composer.github.io/tasks/prerequisites.html that details all dependencies that need to be installed, but are lacking information about the development process. 

We have had questions such as:
- [x] I'm not very familiar with node so I was wondering, is it reasonable to use my own private npm like Sinopia or is there an easier/better way?
- [x] do I need to create/deploy both a digitalproperty-network and digitalproperty-model in my repository or can they just be a single project?
- [x] Can I avoid creating and deploying projects and just create the business network through API calls?

**Comment by samjsmith** [comment]
Thoughts in the room are that we should add these sorts of questions to StackOverflow since people with similar questions will likely just use their favourite search engine to search for answers to their question.
