### ISSUE TITLE
Cannot run Getting Started if it is installed into a path with a space in the name

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#99]
Reported by Sam Winslett.

**Comment by mbwhite** [comment]
This is a case of going over all the bash scripts and modifying them to add in some quotes.

**Comment by dselman** [comment]
To be assigned to Dave.

**Comment by davidkel** [comment]
Have added quotes around directory variables as appropriate for both sample applications and for fabric composer
